version: '3'
services:
  php-simple-server:
    image: gomajijustinliu/php-simple-server:latest
    environment:
      - NAME=Justin
    ports:
      - 80:8080
    depends_on: 
      - redis
    networks:
      - demo-networks
  redis:
    image: redis:4.0
    ports:
      - 6379:6379
    networks:
      - demo-networks
networks:
  demo-networks:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/20